server:
  port: 8761

spring:
  jmx:
    default-domain: mogu_eureka
  application:
    name: mogu_eureka
  security:
    user:
      name: user
      password: password123

eureka:
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 3000
    peer-node-connect-timeout-ms: 3000
  client:
    # false表示不向注册中心注册自己
    registerWithEureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetchRegistry: false
    serviceUrl:
      # 设置与Eureka交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://user:password123@localhost:8761/eureka